import json

mumbai_data_path = '/home/kpit/miscellaneous_code/gt_file_info/mumbai/result.json'
oregon_data_path = '/home/kpit/miscellaneous_code/gt_file_info/oregon/result.json'
virginia_data_path = '/home/kpit/miscellaneous_code/gt_file_info/virginia/result.json'

scenario_uuids = ["SC_ADHWY_ALC_2c", "SC_ADHWY_ALC_2d", "SC_ADHWY_LVF_141a", "SC_ADHWY_LVF_142a", "SC_ADHWY_LVF_143a",
                  "SC_ADHWY_LVF_144a", "SC_ADHWY_LVF_145a", "SC_ADHWY_LVF_2b", "SC_ADHWY_LVF_301a", "SC_ADHWY_LVF_301b",
                  "SC_ADHWY_LVF_302", "SC_ADHWY_LVF_303", "SC_ADHWY_LVF_304", "SC_ADHWY_LVF_306a", "SC_ADHWY_LVF_306b",
                  "SC_ADHWY_LVF_308a", "SC_ADHWY_LVF_308b", "SC_ADHWY_LVF_308c", "SC_ADHWY_LVF_308d",
                  "SC_ADHWY_LVF_310a",
                  "SC_ADHWY_LVF_310b", "SC_ADHWY_LVF_310c", "SC_ADHWY_LVF_310d", "SC_ADHWY_LVF_311a",
                  "SC_ADHWY_LVF_311b",
                  "SC_ADHWY_LVF_311c", "SC_ADHWY_LVF_311d", "SC_ADHWY_LVF_314a", "SC_ADHWY_LVF_315a",
                  "SC_ADHWY_LVF_315b",
                  "SC_ADHWY_LVF_316a", "SC_ADHWY_LVF_316b", "SC_ADHWY_LVF_316c", "SC_ADHWY_LVF_316d",
                  "SC_ADHWY_LVF_317a",
                  "SC_ADHWY_LVF_317b", "SC_ADHWY_LVF_317c", "SC_ADHWY_LVF_317d", "SC_ADHWY_LVF_3i", "SC_ADHWY_LVF_3j",
                  "SC_ADHWY_LVF_80b", "SC_ADHWY_LVF_81i", "SC_ADHWY_LVF_81j", "SC_ADHWY_OVT_3g", "SC_ADHWY_OVT_4n",
                  "SC_ADHWY_TJP_5h", "SC_ADHWY_TJP_8a", "SC_ADHWY_TJP_8b", "SC_ADHWY_LVF_140a", "SC_ADHWY_LVF_152a",
                  "SC_ADHWY_LVF_319c", "SC_ADHWY_ALCCancel_82j", "SC_ADHWY_LVF_309c", "SC_ADHWY_ALC_349b",
                  "SC_ADHWY_ALC_330b", "SC_ADHWY_TJP_83l", "SC_ADHWY_LVF_313b", "SC_ADHWY_ALCCancel_84k",
                  "SC_ADHWY_LVF_318b", "SC_ADHWY_ALC_340c", "SC_ADHWY_ALC_333a", "SC_ADHWY_OVT_84o",
                  "SC_ADHWY_ALC_332d", "SC_ADHWY_LVF_305", "SC_ADHWY_ALCCancel_81l", "SC_ADHWY_ALC_327b",
                  "SC_ADHWY_ALC_346d", "SC_ADHWY_ALC_345b", "SC_ADHWY_ALC_350a", "SC_ADHWY_LVF_309b",
                  "SC_ADHWY_ALC_83d",
                  "SC_ADHWY_OVT_4o", "SC_ADHWY_ALCCancel_5g", "SC_ADHWY_ALC_326c", "SC_ADHWY_ALC_6e",
                  "SC_ADHWY_LVF_307a", "SC_ADHWY_ALCCancel_81p", "SC_ADHWY_ALC_82s", "SC_ADHWY_OVT_2h",
                  "SC_ADHWY_ALCCancel_83x",
                  "SC_ADHWY_TJP_8c", "SC_ADHWY_ALC_83e", "SC_ADHWY_ALC_347b", "SC_ADHWY_LVF_319d",
                  "SC_ADHWY_ALC_326d", "SC_ADHWY_ALC_80c", "SC_ADHWY_LVF_313d", "SC_ADHWY_ALC_7a",
                  "SC_ADHWY_ALC_340b",
                  "SC_ADHWY_TJP_4l",
                  "SC_ADHWY_ALC_83q",
                  "SC_ADHWY_TJP_82l",
                  "SC_ADHWY_TJP_ALC_01",
                  "SC_ADHWY_OVT_7d",
                  "SC_ADHWY_ALCCancel_6j",
                  "SC_ADHWY_OVT_5c",
                  "SC_ADHWY_ALC_81d",
                  "SC_ADHWY_OVT_8d",
                  "SC_ADHWY_OVT_83t",
                  "SC_ADHWY_ALC_325b",
                  "SC_ADHWY_LVF_313a",
                  "SC_ADHWY_ALC_7b",
                  "SC_ADHWY_ALC_332c",
                  "SC_ADHWY_ALC_TJP_08",
                  "SC_ADHWY_ALC_329a",
                  "SC_ADHWY_ALC_329b",
                  "SC_ADHWY_ALCCancel_4u",
                  "SC_ADHWY_ALC_3b",
                  "SC_ADHWY_ALC_345c",
                  "SC_ADHWY_ALC_333d",
                  "SC_ADHWY_ALC_82e",
                  "SC_ADHWY_ALC_346a",
                  "SC_ADHWY_ALC_84s",
                  "SC_ADHWY_ALC_330d",
                  "SC_ADHWY_ALC_4d",
                  "SC_ADHWY_ALC_338",
                  "SC_ADHWY_LVF_319a",
                  "SC_ADHWY_LVF_307c",
                  "SC_ADHWY_ALC_334b",
                  "SC_ADHWY_ALCCancel_83u",
                  "SC_ADHWY_ALCCancel_3m",
                  "SC_ADHWY_ALCCancel_83i",
                  "SC_ADHWY_LVF_318c",
                  "SC_ADHWY_LVF_309a",
                  "SC_ADHWY_ALC_349c",
                  "SC_ADHWY_LVF_307d",
                  "SC_ADHWY_ALC_326a",
                  "SC_ADHWY_OVT_81g",
                  "SC_ADHWY_TJP_82w",
                  "SC_ADHWY_OVT_84n",
                  "SC_ADHWY_ALCCancel_5f",
                  "SC_ADHWY_TJP_83m",
                  "SC_ADHWY_ALC_4f",
                  "SC_ADHWY_ALC_339a",
                  "SC_ADHWY_ALC_320b",
                  "SC_ADHWY_OVT_84g",
                  "SC_ADHWY_ALC_344a",
                  "SC_ADHWY_PAS_ALC_06",
                  "SC_ADHWY_ALCCancel_4x",
                  "SC_ADHWY_ALCCancel_83k",
                  "SC_ADHWY_OVT_80g",
                  "SC_ADHWY_ALC_325a",
                  "SC_ADHWY_OVT_4t",
                  "SC_ADHWY_ALC_83s",
                  "SC_ADHWY_ALCCancel_84j",
                  "SC_ADHWY_ALC_6f",
                  "SC_ADHWY_ALCCancel_84u",
                  "SC_ADHWY_ALC_348a",
                  "SC_ADHWY_OVT_80h",
                  "SC_ADHWY_TJP_4v_StopGo",
                  "SC_ADHWY_LVF_312a",
                  "SC_ADHWY_ALC_331c",
                  "SC_ADHWY_ALC_3d",
                  "SC_ADHWY_ALC_343c",
                  "SC_ADHWY_OVT_84p",
                  "SC_ADHWY_ALC_80d",
                  "SC_ADHWY_ALC_335",
                  "SC_ADHWY_ALC_341b",
                  "SC_ADHWY_ALC_333b",
                  "SC_ADHWY_ALC_327c",
                  "SC_ADHWY_OVT_83n",
                  "SC_ADHWY_ALC_5b",
                  "SC_ADHWY_ALC_326b",
                  "SC_ADHWY_ALC_ADN_01",
                  "SC_ADHWY_ALC_343b",
                  "SC_ADHWY_ALC_5a",
                  "SC_ADHWY_ALC_330c",
                  "SC_ADHWY_TJP_83w",
                  "SC_ADHWY_OVT_4g",
                  "SC_ADHWY_ALC_81e",
                  "SC_ADHWY_OVT_5e",
                  "SC_ADHWY_ALCCancel_84x",
                  "SC_ADHWY_OVT_2f",
                  "SC_ADHWY_ALC_343a",
                  "SC_ADHWY_ALCCancel_84i",
                  "SC_ADHWY_ALCCancel_3l",
                  "SC_ADHWY_TJP_9c",
                  "SC_ADHWY_LVF_313c",
                  "SC_ADHWY_OVTCancel_80j",
                  "SC_ADHWY_ALC_331a",
                  "SC_ADHWY_ALC_81a",
                  "SC_ADHWY_ALCCancel_9d",
                  "SC_ADHWY_ALC_344c",
                  "SC_ADHWY_ALC_4q",
                  "SC_ADHWY_ALC_332b",
                  "SC_ADHWY_ALCCancel_6h",
                  "SC_ADHWY_ALC_321",
                  "SC_ADHWY_ALCCancel_4i",
                  "SC_ADHWY_OVT_80f",
                  "SC_ADHWY_ALC_334a",
                  "SC_ADHWY_ALC_327a",
                  "SC_ADHWY_ALCCancel_4k",
                  "SC_ADHWY_OVT_83g",
                  "SC_ADHWY_OVTCancel_2j",
                  "SC_ADHWY_OVT_82g",
                  "SC_ADHWY_ALC_341d",
                  "SC_ADHWY_ALC_344d",
                  "SC_ADHWY_ALC_349a",
                  "SC_ADHWY_ALC_344b",
                  "SC_ADHWY_TJP_4m",
                  "SC_ADHWY_ALC_84e",
                  "SC_ADHWY_OVT_83o",
                  "SC_ADHWY_ALC_333c",
                  "SC_ADHWY_ALC_345a",
                  "SC_ADHWY_ALC_4s",
                  "SC_ADHWY_OVT_7c",
                  "SC_ADHWY_ALC_9a",
                  "SC_ADHWY_ALC_332a",
                  "SC_ADHWY_ALC_3e",
                  "SC_ADHWY_ALC_4e",
                  "SC_ADHWY_ALCCancel_4j",
                  "SC_ADHWY_OVT_2g",
                  "SC_ADHWY_TJP_7e",
                  "SC_ADHWY_OVT_TJP_6a",
                  "SC_ADHWY_ALC_347a",
                  "SC_ADHWY_PAS_TJP_04",
                  "SC_ADHWY_ALC_327d",
                  "SC_ADHWY_LVF_309d",
                  "SC_ADHWY_ALC_340d",
                  "SC_ADHWY_OVT_5d",
                  "SC_ADHWY_ALC_ADN_02",
                  "SC_ADHWY_ALC_337",
                  "SC_ADHWY_ALC_331b",
                  "SC_ADHWY_ALCCancel_6i",
                  "SC_ADHWY_ALC_345d",
                  "SC_ADHWY_ALC_82q",
                  "SC_ADHWY_ALC_82f",
                  "SC_ADHWY_ALC_84r",
                  "SC_ADHWY_TJP_82m",
                  "SC_ADHWY_ALC_4r",
                  "SC_ADHWY_ALC_331d",
                  "SC_ADHWY_ALC_82r",
                  "SC_ADHWY_ALC_341c",
                  "SC_ADHWY_LVF_319b",
                  "SC_ADHWY_ALC_6g",
                  "SC_ADHWY_ALC_346b",
                  "SC_ADHWY_LVF_318d",
                  "SC_ADHWY_ALC_324",
                  "SC_ADHWY_ALC_322",
                  "SC_ADHWY_LVF_307b",
                  "SC_ADHWY_ALC_320a",
                  "SC_ADHWY_ALC_348b",
                  "SC_ADHWY_ALC_84q",
                  "SC_ADHWY_ALC_PAS_05",
                  "SC_ADHWY_LVF_318a",
                  "SC_ADHWY_OVT_82t",
                  "SC_ADHWY_ALC_349d",
                  "SC_ADHWY_OVT_82p",
                  "SC_ADHWY_ALCCancel_81o",
                  "SC_ADHWY_OVT_83p",
                  "SC_ADHWY_ALCCancel_82u",
                  "SC_ADHWY_ALC_340a",
                  "SC_ADHWY_ALC_323",
                  "SC_ADHWY_TJP_4w",
                  "SC_ADHWY_ALCCancel_82k",
                  "SC_ADHWY_ALC_6d",
                  "SC_ADHWY_ALCCancel_81m",
                  "SC_ADHWY_OVT_4p",
                  "SC_ADHWY_OVT_82o",
                  "SC_ADHWY_ALCCancel_83j",
                  "SC_ADHWY_ALCCancel_3o",
                  "SC_ADHWY_ALCCancel_82i",
                  "SC_ADHWY_LVF_312b",
                  "SC_ADHWY_ALC_TJP_02",
                  "SC_ADHWY_ALC_84d",
                  "SC_ADHWY_ALC_84f",
                  "SC_ADHWY_TJP_OVT_6b",
                  "SC_ADHWY_ALCCancel_80i",
                  "SC_ADHWY_ALC_82d",
                  "SC_ADHWY_ALC_339b",
                  "SC_ADHWY_LVF_312c",
                  "SC_ADHWY_ALC_346c",
                  "SC_ADHWY_ALCCancel_2i",
                  "SC_ADHWY_ALC_336",
                  "SC_ADHWY_ALCCancel_82x",
                  "SC_ADHWY_ALC_83r",
                  "SC_ADHWY_ALC_6c",
                  "SC_ADHWY_ALC_341a",
                  "SC_ADHWY_LVF_312d",
                  "SC_ADHWY_ALC_343d",
                  "SC_ADHWY_ALC_3a",
                  "SC_ADHWY_ALC_83f",
                  "SC_ADHWY_OVT_82n",
                  "SC_ADHWY_ALC_330a"]


def read_json(path):
    with open(path) as file_obj:
        data = json.load(file_obj)
    return data


result = list()
paths = [mumbai_data_path, oregon_data_path, virginia_data_path]
for file_path in paths:
    result.extend(read_json(path=file_path))

scenario_info = list()
for scenario_uuid in scenario_uuids:
    filtered = list(filter(lambda item: scenario_uuid in item['location'], result))
    if filtered:
        scenario_info.append(filtered[0])
    else:
        print("No Matching Result found: ", scenario_uuid)

print(len(scenario_info))
with open("result.json", 'w') as json_file:
    json.dump(scenario_info, json_file, indent=2)
    